# -*- coding: utf-8 -*-
"""CnnSelfAttention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TpFy0dPvElWBdk-fxoBe1NdmwVxUgi5B
"""



from google.colab import drive

drive.mount('/content/drive', force_remount=True)



import os

DATASET_DIR = "/content/drive/MyDrive/log_mel_dataset"

print(os.listdir(DATASET_DIR))



import numpy as np

X = np.load(os.path.join(DATASET_DIR, 'X.npy'))
y = np.load(os.path.join(DATASET_DIR, 'y.npy'))

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")



unique_labels, label_counts = np.unique(y, return_counts=True)
print("Unique Labels:", unique_labels)
print("Label Counts:", label_counts)



import os

DATASET_DIR = "/content/drive/MyDrive/log_mel_dataset"

class_names = sorted([
    d for d in os.listdir(DATASET_DIR)
    if os.path.isdir(os.path.join(DATASET_DIR, d))
])

for i, name in enumerate(class_names):
    print(f"{i} -> {name}")



label_to_name_map = {i: name for i, name in enumerate(class_names)}
y_class_names = np.array([label_to_name_map[label] for label in y])

print("First 10 original labels:", y[:10])
print("First 10 class names labels:", y_class_names[:10])

# Optionally, update y to be the class names if desired, otherwise, use y_class_names as a new variable.
# For now, let's keep 'y' as integers for potential model training steps, and use 'y_class_names' for display/analysis.



unique_class_names, class_name_counts = np.unique(y_class_names, return_counts=True)
print("Unique Class Names:", unique_class_names)
print("Class Name Counts:", class_name_counts)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x=unique_class_names, y=class_name_counts, palette='viridis')
plt.title('Distribution of Classes in the Dataset')
plt.xlabel('Class Name')
plt.ylabel('Number of Samples')
plt.xticks(rotation=45, ha='right') # Rotate labels for better readability
plt.tight_layout()
plt.show()



from sklearn.model_selection import train_test_split

# Split the data into training and validation sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")



from sklearn.utils import class_weight

# Calculate class weights for imbalance handling
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

# Convert class weights to a dictionary format expected by Keras/TensorFlow
class_weights_dict = dict(enumerate(class_weights))

print("Calculated Class Weights (dictionary format):", class_weights_dict)

"""## Build the CNN + Self-Attention Model

We will now define the architecture for our Convolutional Neural Network (CNN) combined with a Self-Attention mechanism. The model will consist of:

1.  **Input Layer**: Takes the log-mel spectrograms as input.
2.  **Convolutional Blocks**: Multiple `Conv2D` layers followed by `BatchNormalization` and `ReLU` activation for feature extraction. `MaxPooling2D` layers will be used for downsampling.
3.  **Self-Attention Mechanism**: A custom or standard attention layer to focus on the most relevant features across the feature maps.
4.  **Global Average Pooling**: Reduces the spatial dimensions of the feature maps.
5.  **Dense Layers**: Fully connected layers for classification.
6.  **Output Layer**: A `Dense` layer with `softmax` activation for multi-class classification.
"""

import tensorflow as tf
from tensorflow.keras import layers, models, backend as K

# Define the input shape based on X_train
# X_train shape is (num_samples, num_mel_bins, num_time_steps)
# For Conv2D, we usually need (height, width, channels). Here, channels=1.
input_shape = (*X_train.shape[1:], 1)
num_classes = len(unique_labels)

print(f"Model input shape: {input_shape}")
print(f"Number of classes: {num_classes}")

class SelfAttention(layers.Layer):
    def __init__(self, channels):
        super(SelfAttention, self).__init__()
        self.channels = channels
        self.query_conv = layers.Conv2D(channels // 8, kernel_size=1, padding='same')
        self.key_conv = layers.Conv2D(channels // 8, kernel_size=1, padding='same')
        self.value_conv = layers.Conv2D(channels, kernel_size=1, padding='same')
        self.gamma = self.add_weight(name='gamma', shape=[1], initializer='zeros', trainable=True)

    def call(self, x):
        batch_size, height, width, C = x.get_shape().as_list()

        proj_query = self.query_conv(x)
        proj_query = K.reshape(proj_query, (-1, height * width, C // 8))
        proj_key = self.key_conv(x)
        proj_key = K.reshape(proj_key, (-1, height * width, C // 8))

        energy = K.batch_dot(proj_query, proj_key, axes=(2, 2))  # (B, N, N)
        attention = K.softmax(energy)

        proj_value = self.value_conv(x)
        proj_value = K.reshape(proj_value, (-1, height * width, self.channels))

        out = K.batch_dot(attention, proj_value)
        out = K.reshape(out, (-1, height, width, self.channels))

        out = self.gamma * out + x
        return out

def build_cnn_attention_model(input_shape, num_classes):
    model_input = layers.Input(shape=input_shape)

    x = model_input

    # First Convolutional Block
    x = layers.Conv2D(32, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)

    # Second Convolutional Block
    x = layers.Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)

    # Third Convolutional Block
    x = layers.Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)

    # Self-Attention Layer
    # We need to ensure the channel dimension is explicit for the attention layer
    attention_channels = x.shape[-1]
    x = SelfAttention(attention_channels)(x)

    # Global Average Pooling
    x = layers.GlobalAveragePooling2D()(x)

    # Dense Layers
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output Layer
    model_output = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs=model_input, outputs=model_output)
    return model

# Build the model
model = build_cnn_attention_model(input_shape, num_classes)

# Display model summary
model.summary()

"""## Compile the Model

Now we compile the model. We'll use:

*   **Optimizer**: Adam optimizer, which is a good default choice.
*   **Loss Function**: `SparseCategoricalCrossentropy` because our labels (`y`) are integers.
*   **Metrics**: `accuracy` to monitor the model's performance during training.
"""

# Compile the model
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

print("Model compiled successfully!")

"""## Train the Model

We will now train the CNN + Self-Attention model using the `fit` method. Key considerations for training include:

*   **Epochs**: The number of times the model will iterate over the entire training dataset.
*   **Batch Size**: The number of samples per gradient update.
*   **Validation Data**: `X_test` and `y_test` will be used to monitor the model's performance on unseen data during training.
*   **Class Weights**: Applied to handle the imbalance in the dataset, ensuring that minority classes are not overlooked.
"""

# Reshape X_train and X_test to add the channel dimension
X_train_reshaped = X_train.reshape(*X_train.shape, 1)
X_test_reshaped = X_test.reshape(*X_test.shape, 1)

print(f"Reshaped X_train shape: {X_train_reshaped.shape}")
print(f"Reshaped X_test shape: {X_test_reshaped.shape}")

history = model.fit(
    X_train_reshaped,
    y_train,
    epochs=100,  # You can adjust the number of epochs
    batch_size=32, # You can adjust the batch size
    validation_data=(X_test_reshaped, y_test),
    class_weight=class_weights_dict
)

"""## Evaluate the Model

After training, it's crucial to evaluate the model's performance on the unseen test dataset. This helps us understand how well the model generalizes to new data. We will compute the loss and accuracy on the test set.
"""

loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

"""## Visualize Training History

Plotting the training and validation loss and accuracy over epochs helps in understanding the learning process, detecting overfitting, and assessing the model's convergence.
"""

import matplotlib.pyplot as plt

# Plot training & validation accuracy values
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.tight_layout()
plt.show()

"""## Detailed Classification Report and Confusion Matrix

To get a more detailed view of the model's performance for each class, we can generate a classification report (precision, recall, f1-score) and a confusion matrix. The confusion matrix will show how many samples of each class were correctly or incorrectly classified.
"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Predict probabilities for the test set
y_pred_probs = model.predict(X_test_reshaped)
# Convert probabilities to predicted class labels
y_pred = np.argmax(y_pred_probs, axis=1)

# Generate classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

from sklearn.metrics import precision_recall_fscore_support
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Get precision, recall, f1-score, and support for each class
precision, recall, f1_score, support = precision_recall_fscore_support(y_test, y_pred, average=None, labels=np.unique(y_test))

metrics_df = pd.DataFrame({
    'Class': class_names,
    'Precision': precision,
    'Recall': recall,
    'F1-score': f1_score,
    'Support': support
})

# Plotting each metric
fig, axes = plt.subplots(4, 1, figsize=(12, 20), sharex=True)

sns.barplot(x='Class', y='Precision', data=metrics_df, ax=axes[0], palette='viridis', hue='Class', legend=False)
axes[0].set_title('Per-Class Precision')
axes[0].set_ylabel('Precision')
axes[0].tick_params(axis='x', rotation=45)

sns.barplot(x='Class', y='Recall', data=metrics_df, ax=axes[1], palette='viridis', hue='Class', legend=False)
axes[1].set_title('Per-Class Recall')
axes[1].set_ylabel('Recall')
axes[1].tick_params(axis='x', rotation=45)

sns.barplot(x='Class', y='F1-score', data=metrics_df, ax=axes[2], palette='viridis', hue='Class', legend=False)
axes[2].set_title('Per-Class F1-score')
axes[2].set_ylabel('F1-score')
axes[2].tick_params(axis='x', rotation=45)

sns.barplot(x='Class', y='Support', data=metrics_df, ax=axes[3], palette='viridis', hue='Class', legend=False)
axes[3].set_title('Per-Class Support')
axes[3].set_ylabel('Support')
axes[3].tick_params(axis='x', rotation=45)
axes[3].set_xlabel('Class Name')

plt.tight_layout()
plt.show()

"""## ROC Curves and ROC-AUC

Receiver Operating Characteristic (ROC) curves are useful for visualizing the performance of a binary classifier as its discrimination threshold is varied. For multi-class problems, we can extend this by computing the ROC curve for each class against the rest (one-vs-rest strategy).
"""

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

# Binarize the true labels for OvR (One-vs-Rest) ROC calculation
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

plt.figure(figsize=(10, 8))
for i in range(num_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_pred_probs[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'ROC curve of {class_names[i]} (area = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random classifier')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - One-vs-Rest')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""## Precision-Recall (PR) Curves and PR-AUC

Precision-Recall curves are particularly informative for imbalanced datasets, as they focus on the positive class. Similar to ROC curves, we can compute PR curves for each class using a one-vs-rest approach.
"""

from sklearn.metrics import precision_recall_curve, average_precision_score

plt.figure(figsize=(10, 8))
for i in range(num_classes):
    precision, recall, _ = precision_recall_curve(y_test_binarized[:, i], y_pred_probs[:, i])
    average_precision = average_precision_score(y_test_binarized[:, i], y_pred_probs[:, i])
    plt.plot(recall, precision, label=f'PR curve of {class_names[i]} (area = {average_precision:.2f})')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve - One-vs-Rest')
plt.legend(loc='lower left')
plt.grid(True)
plt.show()

"""## Attention Map Visualization

To understand where the self-attention mechanism focuses, we can visualize the feature maps output by the `SelfAttention` layer. This involves extracting the output of the attention layer, processing it into a heatmap, and then overlaying it on the original log-mel spectrogram. This heatmap will highlight regions in the input that were given higher importance by the attention module.
"""

import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display
from scipy.ndimage import zoom

SR = 22050 # Sample rate, as defined in cell a2850d25

# --- Helper function to retrieve the SelfAttention layer ---
# The SelfAttention class is defined in cell 79c586ad, which is already executed.
# The 'model' variable is the trained model, also from a previously executed cell.

def get_attention_layer(model):
    for layer in model.layers:
        if isinstance(layer, SelfAttention):
            return layer
    return None

attention_layer = get_attention_layer(model)

if attention_layer is None:
    print("Error: SelfAttention layer not found in the model.")
else:
    # Create a new model that outputs both the final predictions and the output of the SelfAttention layer
    attention_model = tf.keras.Model(inputs=model.input, outputs=[model.output, attention_layer.output])

    # Select a sample from the test set for visualization
    sample_idx = 1  # Updated to visualize 'chainsaw_sounds'
    input_sample = X_test_reshaped[sample_idx:sample_idx+1]

    # Get predictions and attention features
    predictions, attention_features = attention_model.predict(input_sample, verbose=0)

    # Process attention_features for visualization:
    # 1. Average across the channels to get a single heatmap (H, W)
    attention_map = np.mean(attention_features[0], axis=-1)

    # 2. Normalize the map to a [0, 1] range for better visualization
    attention_map = (attention_map - attention_map.min()) / (attention_map.max() - attention_map.min() + 1e-8)

    # Original log-mel spectrogram for overlay
    original_spectrogram = input_sample[0, :, :, 0] # Remove batch and channel dimensions

    # Upsample the attention map to the original spectrogram size
    # The attention map has a smaller spatial dimension due to MaxPooling layers before it.
    # The scaling factor is (original_height / attention_map_height, original_width / attention_map_width)
    upsampling_factor_height = original_spectrogram.shape[0] / attention_map.shape[0]
    upsampling_factor_width = original_spectrogram.shape[1] / attention_map.shape[1]

    upsampled_attention_map = zoom(attention_map,
                                   (upsampling_factor_height, upsampling_factor_width),
                                   order=1) # Use linear interpolation

    # Plotting
    plt.figure(figsize=(12, 7))
    librosa.display.specshow(original_spectrogram, sr=SR, x_axis='time', y_axis='mel', cmap='coolwarm')
    plt.imshow(upsampled_attention_map, cmap='jet', alpha=0.5, origin='lower', aspect='auto',
               extent=[0, original_spectrogram.shape[1], 0, original_spectrogram.shape[0]])
    plt.colorbar(label='Attention Intensity')
    plt.title(f'Attention Map Overlay on Log-Mel Spectrogram\nTrue Class: {class_names[y_test[sample_idx]]}, Predicted: {class_names[np.argmax(predictions)]}')
    plt.tight_layout()
    plt.show()

sample_idx = np.where(y_test == 1)[0][0]
print(f"Updated sample_idx to {sample_idx} for class: {class_names[y_test[sample_idx]]}")

"""## Grad-CAM (Gradient-weighted Class Activation Mapping)

Grad-CAM helps visualize the regions in the input that are most important for the model's classification decision. It does this by using the gradients of the target concept (e.g., the predicted class score) flowing into the final convolutional layer. The heatmaps generated by Grad-CAM highlight discriminative regions in the input that contribute to the model's prediction.

### Visualizing Attention Map and Grad-CAM for all Classes

To ensure we examine how the model attends to and highlights features for each distinct sound category, we will now generate Attention Map and Grad-CAM visualizations for a sample from each class. We will iterate through all unique class IDs, find the first available sample in `y_test` for that class, and then plot the visualizations.

### Attention Consistency Test

To evaluate the robustness of our attention mechanism, we will perform an **Attention Consistency Test**. This involves:

1.  Selecting a sample from each class.
2.  Generating its original attention map.
3.  Creating slightly shifted versions of the input spectrogram (e.g., shifting by a few pixels horizontally and vertically).
4.  Generating attention maps for these shifted input spectrograms.
5.  Visually comparing the original and shifted attention maps to see if the model's focus remains consistent despite minor input perturbations. Ideally, the attention should still highlight the same critical regions.
"""

from scipy.ndimage import shift as ndimage_shift

def shift_spectrogram(spectrogram_2d, shift_pixels=(0, 0)):
    """
    Shifts a 2D spectrogram.

    Args:
        spectrogram_2d (np.ndarray): The 2D spectrogram (e.g., original_spectrogram[0, :, :, 0]).
        shift_pixels (tuple): (shift_y, shift_x) in pixels.

    Returns:
        np.ndarray: The shifted 2D spectrogram.
    """
    # Note: ndimage_shift expects (height_shift, width_shift)
    # We use mode='constant' and cval=spectrogram_2d.min() to fill new areas with the minimum spectrogram value
    return ndimage_shift(spectrogram_2d, shift_pixels, mode='constant', cval=spectrogram_2d.min())

import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display
from scipy.ndimage import zoom
import tensorflow as tf

SR = 22050 # Sample rate, as defined in cell a2850d25

# --- Helper function to retrieve the SelfAttention layer ---
def get_attention_layer(model):
    for layer in model.layers:
        if isinstance(layer, SelfAttention):
            return layer
    return None

attention_layer = get_attention_layer(model)

if attention_layer is None:
    print("Error: SelfAttention layer not found in the model.")
else:
    attention_model = tf.keras.Model(inputs=model.input, outputs=[model.output, attention_layer.output])

    print("Generating Attention Consistency Test visualizations for all classes...")
    for class_id in np.unique(y_test):
        # Find the first index in y_test that matches the current class_id
        sample_indices = np.where(y_test == class_id)[0]
        if len(sample_indices) == 0:
            print(f"No samples found for class ID {class_id} ({class_names[class_id]}) in y_test. Skipping.")
            continue

        sample_idx = sample_indices[0]
        input_sample = X_test_reshaped[sample_idx:sample_idx+1]
        original_spectrogram = input_sample[0, :, :, 0]

        # --- Original Attention Map ---
        predictions_orig, attention_features_orig = attention_model.predict(input_sample, verbose=0)
        attention_map_orig = np.mean(attention_features_orig[0], axis=-1)
        attention_map_orig = (attention_map_orig - attention_map_orig.min()) / (attention_map_orig.max() - attention_map_orig.min() + 1e-8)

        upsampling_factor_height = original_spectrogram.shape[0] / attention_map_orig.shape[0]
        upsampling_factor_width = original_spectrogram.shape[1] / attention_map_orig.shape[1]
        upsampled_attention_map_orig = zoom(attention_map_orig,
                                            (upsampling_factor_height, upsampling_factor_width),
                                            order=1) # Use linear interpolation

        # --- Shifted Attention Map ---
        # Apply a small shift to the spectrogram (e.g., 2 pixels down, 2 pixels right)
        shift_pixels = (2, 2) # (y_shift, x_shift)
        shifted_spectrogram_2d = shift_spectrogram(original_spectrogram, shift_pixels)
        shifted_input_sample = shifted_spectrogram_2d[np.newaxis, ..., np.newaxis]

        predictions_shifted, attention_features_shifted = attention_model.predict(shifted_input_sample, verbose=0)
        attention_map_shifted = np.mean(attention_features_shifted[0], axis=-1)
        attention_map_shifted = (attention_map_shifted - attention_map_shifted.min()) / (attention_map_shifted.max() - attention_map_shifted.min() + 1e-8)

        upsampled_attention_map_shifted = zoom(attention_map_shifted,
                                             (upsampling_factor_height, upsampling_factor_width),
                                             order=1) # Use linear interpolation

        # --- Plotting Original vs. Shifted Attention Maps ---
        fig, axes = plt.subplots(1, 2, figsize=(20, 7))

        # Original Plot
        librosa.display.specshow(original_spectrogram, sr=SR, x_axis='time', y_axis='mel', cmap='coolwarm', ax=axes[0])
        axes[0].imshow(upsampled_attention_map_orig, cmap='jet', alpha=0.5, origin='lower', aspect='auto',
                   extent=[0, original_spectrogram.shape[1], 0, original_spectrogram.shape[0]])
        axes[0].set_title(f'Original Spectrogram & Attention Map\nTrue: {class_names[y_test[sample_idx]]}, Pred: {class_names[np.argmax(predictions_orig)]}')
        axes[0].set_xlabel('Time')
        axes[0].set_ylabel('Hz')
        # Add a colorbar for the original plot's attention intensity, adjusting its position
        # cax_orig = fig.add_axes([axes[0].get_position().x1 + 0.01, axes[0].get_position().y0, 0.01, axes[0].get_position().height])
        # fig.colorbar(axes[0].images[-1], cax=cax_orig, label='Attention Intensity')

        # Shifted Plot
        librosa.display.specshow(shifted_spectrogram_2d, sr=SR, x_axis='time', y_axis='mel', cmap='coolwarm', ax=axes[1])
        axes[1].imshow(upsampled_attention_map_shifted, cmap='jet', alpha=0.5, origin='lower', aspect='auto',
                   extent=[0, original_spectrogram.shape[1], 0, original_spectrogram.shape[0]])
        axes[1].set_title(f'Shifted Spectrogram & Attention Map (Shift: {shift_pixels})\nTrue: {class_names[y_test[sample_idx]]}, Pred: {class_names[np.argmax(predictions_shifted)]}')
        axes[1].set_xlabel('Time')
        # Add a single colorbar for the shifted plot, for clarity
        cbar = fig.colorbar(axes[1].images[-1], ax=axes.ravel().tolist(), shrink=0.75, label='Attention Intensity')

        plt.tight_layout(rect=[0, 0, 0.95, 1]) # Adjust layout to make space for the colorbar
        plt.show()

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display

SR = 22050 # Sample rate, as defined in cell a2850d25

# --- Create a functional model to extract intermediate layer outputs ---
def build_cnn_attention_model_named_conv(input_shape, num_classes):
    model_input = tf.keras.layers.Input(shape=input_shape)
    x = model_input

    x = tf.keras.layers.Conv2D(32, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    x = tf.keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    last_conv_output = tf.keras.layers.Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same', name='last_conv_layer')(x)
    x = tf.keras.layers.BatchNormalization()(last_conv_output)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    attention_channels = x.shape[-1]
    x = SelfAttention(attention_channels)(x)

    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(256, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    model_output = tf.keras.layers.Dense(num_classes, activation='softmax')(x)

    return tf.keras.Model(inputs=model_input, outputs=model_output, name="GradCAM_Model")

gradcam_model = build_cnn_attention_model_named_conv(input_shape, num_classes)
gradcam_model.set_weights(model.get_weights())

last_conv_layer_name = 'last_conv_layer'

print("Generating Grad-CAM visualizations for all classes...")
for class_id in np.unique(y_test):
    # Find the first index in y_test that matches the current class_id
    sample_indices = np.where(y_test == class_id)[0]
    if len(sample_indices) == 0:
        print(f"No samples found for class ID {class_id} ({class_names[class_id]}) in y_test. Skipping.")
        continue

    sample_idx = sample_indices[0]
    input_sample = X_test_reshaped[sample_idx:sample_idx+1]
    true_label = y_test[sample_idx]

    preds = gradcam_model.predict(input_sample, verbose=0)
    predicted_class = np.argmax(preds[0])
    predicted_score = preds[0][predicted_class]

    gradcam_sub_model = tf.keras.models.Model(
        inputs=gradcam_model.inputs,
        outputs=[gradcam_model.get_layer(last_conv_layer_name).output, gradcam_model.output]
    )

    with tf.GradientTape() as tape:
        last_conv_layer_output, predictions = gradcam_sub_model(input_sample)
        tape.watch(last_conv_layer_output)
        class_channel = predictions[:, predicted_class]

    grads = tape.gradient(class_channel, last_conv_layer_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    heatmap = last_conv_layer_output[0] @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0)
    max_val = tf.reduce_max(heatmap)
    if max_val == 0:
        heatmap = heatmap * 0
    else:
        heatmap = heatmap / max_val

    heatmap = heatmap.numpy()

    original_spectrogram = input_sample[0, :, :, 0]

    upsampling_factor_height = original_spectrogram.shape[0] / heatmap.shape[0]
    upsampling_factor_width = original_spectrogram.shape[1] / heatmap.shape[1]

    upsampled_heatmap = zoom(heatmap,
                             (upsampling_factor_height, upsampling_factor_width),
                             order=1)

    plt.figure(figsize=(12, 7))
    librosa.display.specshow(original_spectrogram, sr=SR, x_axis='time', y_axis='mel', cmap='coolwarm')
    plt.imshow(upsampled_heatmap, cmap='jet', alpha=0.5, origin='lower', aspect='auto',
               extent=[0, original_spectrogram.shape[1], 0, original_spectrogram.shape[0]])
    plt.colorbar(label='Grad-CAM Intensity')
    plt.title(f'Grad-CAM Heatmap Overlay on Log-Mel Spectrogram\nTrue Class: {class_names[true_label]}, Predicted: {class_names[predicted_class]} (Score: {predicted_score:.2f})')
    plt.tight_layout()
    plt.show()

"""## Ablation on Attention Tests

An ablation test for the attention mechanism involves evaluating the model's performance when the attention layer is removed or bypassed. This helps determine the contribution of the attention mechanism to the overall model performance.

For a full ablation study, it's ideal to retrain the model without the attention layer from scratch. However, for a quick assessment, we can build a structurally similar model that omits the attention layer and evaluate it. We'll load the weights from the original model for all *shared* layers to see the impact of *just* the attention layer being absent, without a full re-training cycle.
"""

import tensorflow as tf

# --- Define a model architecture WITHOUT the SelfAttention layer ---
# The SelfAttention class is defined in cell 79c586ad, which is already executed.

def build_cnn_no_attention_model(input_shape, num_classes):
    model_input = tf.keras.layers.Input(shape=input_shape)
    x = model_input

    x = tf.keras.layers.Conv2D(32, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    x = tf.keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    x = tf.keras.layers.Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)

    # !!! SelfAttention layer is omitted here !!!

    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(256, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    model_output = tf.keras.layers.Dense(num_classes, activation='softmax')(x)

    return tf.keras.Model(inputs=model_input, outputs=model_output, name="NoAttention_Model")

# Build the no-attention model
no_attention_model = build_cnn_no_attention_model(input_shape, num_classes)

# Compile the no-attention model (same as the original)
no_attention_model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

# --- Transfer weights from the original model to the no-attention model ---
# This is a bit manual as the architectures are slightly different (one layer removed)
# We will copy weights for layers that exist in both models.

print("Attempting to transfer weights from original model to no-attention model...")
original_layers = {layer.name: layer for layer in model.layers}

for layer_no_att in no_attention_model.layers:
    if layer_no_att.name in original_layers:
        original_layer = original_layers[layer_no_att.name]
        if original_layer.weights and layer_no_att.weights:
            # Ensure shapes match before setting weights
            if all(o.shape == n.shape for o, n in zip(original_layer.get_weights(), layer_no_att.get_weights())):
                layer_no_att.set_weights(original_layer.get_weights())
                # print(f"  Transferred weights for layer: {layer_no_att.name}")
            else:
                print(f"  Skipping weight transfer for {layer_no_att.name} due to shape mismatch.")

print("Weight transfer attempt complete.\n")

# Evaluate the no-attention model on the test set
print("Evaluating the model without attention layer...")
loss_no_att, accuracy_no_att = no_attention_model.evaluate(X_test_reshaped, y_test, verbose=0)

print(f"Original Model Test Loss: {loss:.4f}")
print(f"Original Model Test Accuracy: {accuracy:.4f}")
print(f"No-Attention Model Test Loss: {loss_no_att:.4f}")
print(f"No-Attention Model Test Accuracy: {accuracy_no_att:.4f}")

print("\nComparison of performance with and without attention layer:")
if accuracy_no_att < accuracy:
    print(f"The original model (with attention) showed higher accuracy ({accuracy:.4f}) compared to the model without attention ({accuracy_no_att:.4f}).")
elif accuracy_no_att > accuracy:
    print(f"The model without attention ({accuracy_no_att:.4f}) surprisingly showed higher accuracy than the original model (with attention) ({accuracy:.4f}). This might indicate the attention mechanism didn't provide a significant benefit or could be optimized further.")
else:
    print("The accuracy remained the same with and without the attention layer.")

"""## Inference on `DS_sound_samples` from Google Drive

Now, we will demonstrate how to perform inference on multiple new audio files from the `DS_sound_samples` directory located in your Google Drive. For each class, we will select at least 10 samples (or all available if fewer than 10), preprocess them, and then predict their class using our trained CNN + Self-Attention model. This will simulate real-world usage where you might have new audio data to classify.
"""

import librosa
import librosa.display
import math

# Define the directory containing the sound samples
SOUND_SAMPLES_DIR = "/content/drive/MyDrive/DS_sound_samples"

# Assuming the audio files are directly inside class subdirectories within SOUND_SAMPLES_DIR
# The structure is expected to be: DS_sound_samples/class_name/audio_file.wav

# Parameters for log-mel spectrogram extraction (should match training data preprocessing)
SR = 22050 # Sample rate
N_MELS = 128 # Number of mel bins
FMAX = 8000 # Maximum frequency
TARGET_TIME_STEPS = 216 # Expected number of time steps for the spectrogram

def preprocess_audio_for_inference(audio_path, sr=SR, n_mels=N_MELS, fmax=FMAX, target_time_steps=TARGET_TIME_STEPS):
    """Loads an audio file, extracts its log-mel spectrogram, and reshapes it for model inference."""
    try:
        audio, _ = librosa.load(audio_path, sr=sr)
        mel_spectrogram = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=n_mels, fmax=fmax)
        log_mel_spectrogram = librosa.power_to_db(mel_spectrogram, ref=np.max)

        # Handle time steps: pad or crop to match TARGET_TIME_STEPS
        current_time_steps = log_mel_spectrogram.shape[1]
        if current_time_steps < target_time_steps:
            # Pad with zeros
            padding = np.zeros((n_mels, target_time_steps - current_time_steps))
            log_mel_spectrogram = np.concatenate((log_mel_spectrogram, padding), axis=1)
        elif current_time_steps > target_time_steps:
            # Crop
            log_mel_spectrogram = log_mel_spectrogram[:, :target_time_steps]

        # Reshape for model input: (1, N_MELS, TARGET_TIME_STEPS, 1)
        # Add batch dimension and channel dimension
        model_input = log_mel_spectrogram[np.newaxis, ..., np.newaxis]
        return model_input
    except Exception as e:
        print(f"Error processing {audio_path}: {e}")
        return None

print(f"Sound samples directory: {SOUND_SAMPLES_DIR}")

print("Performing inference on samples from each class...")

# Iterate through each class folder in the dataset directory
for class_idx, class_name in enumerate(class_names):
    class_folder_path = os.path.join(SOUND_SAMPLES_DIR, class_name)
    if not os.path.isdir(class_folder_path):
        print(f"Skipping {class_folder_path}: Not a directory or does not exist.")
        continue

    print(f"\n--- Class: {class_name} (True Label: {class_idx}) ---")
    audio_files = [os.path.join(class_folder_path, f) for f in os.listdir(class_folder_path) if f.endswith(('.wav', '.flac', '.ogg', '.mp3'))]

    # Take at least 10 samples, or all if fewer than 10
    samples_to_test = audio_files[:min(10, len(audio_files))]

    if not samples_to_test:
        print(f"No audio files found in {class_folder_path}")
        continue

    for i, audio_file_path in enumerate(samples_to_test):
        print(f"  Sample {i+1}: {os.path.basename(audio_file_path)}")
        preprocessed_spectrogram = preprocess_audio_for_inference(audio_file_path)

        if preprocessed_spectrogram is not None:
            # Perform prediction
            predictions = model.predict(preprocessed_spectrogram, verbose=0)
            predicted_label = np.argmax(predictions, axis=1)[0]
            predicted_class_name = label_to_name_map[predicted_label]

            print(f"    True Class: {class_name}")
            print(f"    Predicted Class: {predicted_class_name}")
            print(f"    Probabilities: {predictions[0]}")
        else:
            print("    Preprocessing failed for this sample.")

print("\nInference complete for selected samples.")

"""## Convert Model to TFLite and Save to Google Drive

This section converts the trained Keras model into TensorFlow Lite format, which is optimized for on-device machine learning inference. The TFLite model will then be saved to a specified location in your Google Drive.
"""

import tensorflow as tf
import os

# Define the directory to save the TFLite model
TFLITE_MODEL_DIR = "/content/drive/MyDrive/CNN_SELF_ATTENTION"
os.makedirs(TFLITE_MODEL_DIR, exist_ok=True)

# Define the path for the TFLite model file
TFLITE_MODEL_PATH = os.path.join(TFLITE_MODEL_DIR, "cnn_self_attention_model.tflite")

# Convert the Keras model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TFLite model to Google Drive
with open(TFLITE_MODEL_PATH, 'wb') as f:
    f.write(tflite_model)

print(f"TFLite model saved to: {TFLITE_MODEL_PATH}")